### ISSUE TITLE
RetroMCP failed to start the game while opening with zulu JDK

### ISSUE THREAD

**Issue by IRaKaNI** [MCPHackers/RetroMCP-Java#58] opened 2023-04-20 21:23 UTC

**Comment by mudkipdev** [comment] 2023-04-20 21:33
This information alone is not enough to solve the issue

**Comment by Lassebq** [comment] 2023-04-21 09:15
![image](https://user-images.githubusercontent.com/68742864/233597380-5b91a84a-6200-4f60-aa1f-d2c1fe7efa0d.png)
The issue is this

**Comment by Lassebq** [comment] 2023-04-28 20:05
Closing due to lack of info

**Closed by Lassebq** 2023-04-28 20:05 UTC
