### ISSUE TITLE
Outdated patches

### ISSUE THREAD

**Issue by Fancymaster1** [MCPHackers/RetroMCP-Java#15] opened 2022-06-13 03:50 UTC
Fails in latest build of pre3, also fails in pre2 release.
Patching does not fail in pre1 release, however.

![image](https://user-images.githubusercontent.com/58319364/173275502-e55e1b5a-a319-4e4c-9d9c-271e2eaf5b9c.png)

No idea if other versions of Minecraft fails to patch or not.

**Comment by genericpnpmonit0r** [comment] 2022-06-13 17:39
This is caused by a decompiler update in pre2 and pre3. I would recommend using pre1 or 0.3 for now.

**Comment by Fancymaster1** [comment] 2022-07-12 00:53
Update as of 07.11.2022: Decompiling pretty much any version seems to fail now.

May have something to do with `mappings.tiny` not existing.
![javaw_GTrgNvcjSS](https://user-images.githubusercontent.com/58319364/178384723-7f13ce4e-21f9-4a17-a0d0-611d0ae4d837.png)

All obfuscated versions of Minecraft will fail to decompile. (either due to `mappings.tiny` not existing or something else)
![javaw_oeHPGNikv3](https://user-images.githubusercontent.com/58319364/178384851-7ecf1ecd-0c95-40cc-af9f-00125eab5d5c.png)

**Comment by PhoenixVX** [comment] 2022-07-12 02:32
Use v1.0-pre1 or v0.3.

v1.0pre2+ uses a different decompiler, which breaks the previous patches.

**Comment by Lassebq** [comment] 2022-07-12 11:16
Latest commit includes experimental features and if you attempt to decompile using current data from our web storage it'll fail
`conf` contents will be changed to use `mappings.tiny` instead of `client.tiny` and `server.tiny`, as well as exceptions.exc instead of separate ones for client and server

**Comment by Lassebq** [comment] 2022-07-12 11:22
Use pre1 as all the patches were made for that version and weren't updated since then. New versions work however. Anything after inf-630 is mostly decompilable in pre3

**Comment by PhoenixVX** [comment] 2022-08-08 23:46
Closing as this issue is no longer relevant.

**Closed by PhoenixVX** 2022-08-08 23:46 UTC
